-- Agenda Evolução — schema do Supabase (projeto indapxewhfobzxnwswhy)
--
-- Reconstruído a partir do uso real das tabelas em index.html (chamadas sbGet/sbPost/sbPatch),
-- não é um dump direto do Supabase. Confira tipos exatos (ex: id bigint vs uuid, defaults)
-- direto no Table Editor / SQL Editor do Supabase antes de rodar isso como migration.
--
-- ATENCAO (risco de seguranca): o app acessa essas tabelas direto do navegador usando a anon
-- key publica, sem camada de autenticacao do Supabase Auth. Isso so e seguro se o Row Level
-- Security (RLS) estiver habilitado e as policies estiverem configuradas corretamente
-- (ou intencionalmente abertas, sabendo do risco). Vale confirmar isso no painel do Supabase.

-- ============================================================
-- eventos: reuniões, entrevistas, rodízios e outros eventos da agenda
-- ============================================================
create table if not exists eventos (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  tipo         text not null,              -- 'reuniao' | 'entrevista' | 'rodizio' | 'outro'
  titulo       text not null,
  data         date not null,
  hora         time not null,
  local        text,
  participantes text,
  status       text,                       -- ex: 'Confirmado', 'Agendado', 'Escalado', 'Planejado'
  visibilidade text default 'todos',       -- 'todos' | 'gestor' | perfil único | lista separada por vírgula
  recorrente   boolean not null default false,
  recur_interval integer,                  -- dias entre repetições (ex: 7, 14, 21, 30)
  recur_end    date,                       -- data final da recorrência
  recur_group  uuid,                       -- agrupa todas as instâncias geradas pela mesma recorrência
  ata          jsonb not null default '[]' -- array de {topico, responsavel, prazo}
);

-- ============================================================
-- rodizios: escala de revezamento de fim de semana (professor + recepcionista)
-- ============================================================
create table if not exists rodizios (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  semana       text not null,              -- rótulo legível, ex: "5 e 6 de Jul"
  data_inicio  date not null,
  prof_nome    text not null,
  prof_init    text,                       -- iniciais para o avatar
  prof_color   integer default 0,
  recep_nome   text not null,
  recep_init   text,
  recep_color  integer default 1,
  recorrente   boolean not null default false,
  recur_interval integer,                  -- dias entre repetições (ex: 7, 14, 21)
  recur_end    date,
  recur_group  uuid
);

-- ============================================================
-- equipe: professores e recepcionistas cadastrados (usados nos selects de rodízio)
-- ============================================================
create table if not exists equipe (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  nome         text not null,
  cargo        text not null,              -- 'Professor' | 'Recepção' | 'Outro'
  ativo        boolean not null default true
);

-- ============================================================
-- config: linha única com identidade da empresa e PIN do Gestor
-- ============================================================
create table if not exists config (
  id           bigint generated by default as identity primary key,
  pin          text default '1234',
  empresa_nome text default 'Evolução Fit',
  empresa_short text default 'Evolução'
);
